### ISSUE TITLE
Wrong Card Type

### ISSUE THREAD

**Issue by sean-hill** [Shortbreaks/iinChecker#25]
Check this out:

`https://bins.ribbon.co/api/v1/bins/442742`

vs 

`http://www.binlist.net/` using `442742`

Binlist doesn't return a card type, but ribbon.co does.

ribbon.co says this card type is debit, but this repo says it's credit. I'm assuming that since binlist didn't return a card type that it defaults to credit? How can this be fixed because my card truly is a debit card. Thanks!

**Comment by kevinhodges** [comment]
Hi @sean-hill, Binlist seem to have added a whole new bunch of ranges recently which previously they didn't support hence why your now seeing the outcome you've detailed above.  We're going to quick fix the module by performing the ribbon.co check first as this is now the most up to date data set.

Once we've got a fix up we will then look at what we can do with a more sophisticated approach.

Hope this helps.

**Comment by kevinhodges** [comment]
Hi @sean-hill, i've now pushed https://github.com/Shortbreaks/iinChecker/releases/tag/0.1.9, hopefully this will fix your problem.

**Comment by sean-hill** [comment]
Thans @kevinhodges!
